name: Test and Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: pip install pytest httpx
      - run: pytest test_main.py -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Runner IP
        id: ip
        run: echo "ip=$(curl -s https://api.ipify.org)" >> "$GITHUB_OUTPUT"

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: open SSH for this run only
        run : |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.SECURITY_GROUP_ID }} \
            --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ip }}/32

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY  }}
          script: |
              cd ~/app
              git pull origin main
              ~/app/venv/bin/pip install -r requirements.txt
              sudo systemctl restart fraud-api
              sleep 2
              curl -f http://127.0.0.1:8000/health || exit 1
      
      - name: Revoke SSH access
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.SECURITY_GROUP_ID }} \
            --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ip }}/32
